# Generated by Django 3.1.7 on 2021-06-07 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210606_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='human_resource',
            name='phone',
            field=models.CharField(default='na', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
