# Generated by Django 3.1.7 on 2021-06-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_purchasemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='age',
            field=models.CharField(choices=[('Teenager', '21 to 32'), ('elder', '33 to 44')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='request_for',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_is_complete',
            field=models.BooleanField(default='True'),
        ),
    ]
