# Generated by Django 3.1.7 on 2021-06-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210624_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='durations',
            field=models.CharField(choices=[('1Day', '1'), ('2Day', '2'), ('3Day', '3'), ('4Day', '4'), ('5Day', '5'), ('6Day', '6'), ('7Day', '7'), ('8Day', '8'), ('9Day', '9'), ('10Day', '10')], max_length=100),
        ),
    ]
