# Generated by Django 3.1.7 on 2021-06-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210624_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='image_1',
            new_name='image',
        ),
    ]
